"""
Example ETL DAG generated by ETLab.
This is a sample DAG to verify Airflow integration works correctly.
"""

from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.operators.empty import EmptyOperator

# DAG default arguments
default_args = {
    'owner': 'etlab',
    'depends_on_past': False,
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

# DAG definition
with DAG(
    dag_id='example_etl_dag',
    default_args=default_args,
    description='Example ETL pipeline generated by ETLab',
    schedule_interval=None,
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=['etlab', 'example'],
) as dag:

    # Start task
    start = EmptyOperator(
        task_id='start',
    )

    # Extract task
    def extract_data():
        print("Extracting data from source...")
        return {"records": 100}

    extract = PythonOperator(
        task_id='extract',
        python_callable=extract_data,
    )

    # Transform task
    def transform_data(**context):
        data = context['ti'].xcom_pull(task_ids='extract')
        print(f"Transforming {data['records']} records...")
        return {"processed": data['records']}

    transform = PythonOperator(
        task_id='transform',
        python_callable=transform_data,
    )

    # Load task
    def load_data(**context):
        data = context['ti'].xcom_pull(task_ids='transform')
        print(f"Loading {data['processed']} records to destination...")
        return {"loaded": data['processed']}

    load = PythonOperator(
        task_id='load',
        python_callable=load_data,
    )

    # End task
    end = EmptyOperator(
        task_id='end',
    )

    # Task dependencies
    start >> extract >> transform >> load >> end
